### ISSUE TITLE
Ask what the problem is 

### ISSUE THREAD

**Issue by zbdg123** [OpenYiff/Kemono2#176]
kemono-archiver      | Traceback (most recent call last):
kemono-archiver      |   File "daemon.py", line 4, in <module>
kemono-archiver      |     from src.lib import server
kemono-archiver      |   File "/app/src/lib/server.py", line 20, in <module>
kemono-archiver      |     from development import development
kemono-archiver      |   File "/app/development/__init__.py", line 13, in <module>
kemono-archiver      |     from .lib import importer as kemono_dev
kemono-archiver      |   File "/app/development/lib/importer/__init__.py", line 4, in <module>
kemono-archiver      |     from .importer import run_paysite_import as import_posts
kemono-archiver      |   File "/app/development/lib/importer/importer.py", line 10, in <module>
kemono-archiver      |     from development.internals import dev_random, service_name
kemono-archiver      |   File "/app/development/internals/__init__.py", line 2, in <module>
kemono-archiver      |     from .assets import assets_folder, file_extensions, asset_files
kemono-archiver      |   File "/app/development/internals/assets.py", line 8, in <module>
kemono-archiver      |     asset_files = get_folder_file_paths(assets_folder, file_extensions)
kemono-archiver      |   File "/app/development/utils/files.py", line 23, in get_folder_file_paths
kemono-archiver      |     raise ValueError(f'Path "{folder}" is not a folder.')
kemono-archiver      | ValueError: Path "/app/development/assets" is not a folder.

**Comment by BassOfBass** [comment]
Update the archiver submodule to the latest master.

**Comment by BassOfBass** [comment]
Was it solved?
