### ISSUE TITLE
How should I fill in the SECRET_KEY=

### ISSUE THREAD

**Issue by yijueEX** [OpenYiff/Kemono2#179]
I get an error message when I try to run server.py:
Traceback (most recent call last):
  File "C:\Users\邦邦\kemono2\server.py", line 68, in <module>
    app.config.from_pyfile('flask.cfg')
  File "C:\Users\邦邦\kemono2\flask\config.py", line 119, in from_pyfile
    exec(compile(config_file.read(), filename, "exec"), d.__dict__)
  File "C:\Users\邦邦\kemono2\flask.cfg", line 5
    SECRET_KEY=
              ^
SyntaxError: invalid syntax

I filled in some random numbers, but it came up with the following prompt:
Failed to connect to the database:  could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?

I'm pretty sure there are no programs running on port 5432.
what should I do

**Comment by yijueEX** [comment]
Or what do I do after I complete the readMe steps

**Comment by BassOfBass** [comment]
`SECRET_KEY` has to be a string and therefore surrounded by `"` marks.

**Comment by yijueEX** [comment]
I have added ''. But I also received the second question above:

Failed to connect to the database:  could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?

Self test according to the above solution. I can connect to 127.0.0.1, localhost and localhost:80. There is no problem with my localhost, so I checked the port connection (Port 5432). No problem. How can I solve the problem? At the same time, what is this python package or the python program?
